### ISSUE TITLE
Autarkysoft.Bitcoin 0.9.0 is not compatible with net50

### ISSUE THREAD

**Issue by MarkRLV** [Coding-Enthusiast/FinderOuter#19]
I freshly installed net50 and Autarkysoft.Bitcoin 0.9.0 

I am getting the error:  
Error	NU1202	Package Autarkysoft.Bitcoin 0.9.0 is not compatible with net50 (.NETFramework,Version=v5.0). Package Autarkysoft.Bitcoin 0.9.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)	Tests	
C:\Users\<me>\Source\Repos\FinderOuter\Src\Tests\Tests.csproj	1

**Comment by Coding-Enthusiast** [comment]
Please check your Nuget Package Manager version and make sure it is updated? There seems to have been a bug in pre 5.x versions.
