### ISSUE TITLE
Estimated Time Calculation

### ISSUE THREAD

**Issue by emanyaster** [Coding-Enthusiast/FinderOuter#21]
I lost 19 characters from the end of my private key starting with K. It has been working for about 5 days but unfortunately it has not yielded any results. How can the estimated time be calculated?

**Comment by Coding-Enthusiast** [comment]
Please refer to #20

**Comment by sezginyildirim91** [comment]
You'll get faster results with Bitcrack. Write to my e-mail address: sezginyildirim@msn.com
