### ISSUE TITLE
Coinbase 12 word seed

### ISSUE THREAD

**Issue by lampkamonika** [Coding-Enthusiast/FinderOuter#22]
How to recover 12 seeds to coinbase wallet

**Comment by Coding-Enthusiast** [comment]
You should explain what your problem is exactly.  
- Do you have all the 12 words?  
- Do you know any of your addresses?
- Do you know the derivation path that Coinbase wallet uses?

**Comment by lampkamonika** [comment]
I have none if the words but I know address

**Comment by Coding-Enthusiast** [comment]
> I have none if the words

There is nothing you can except contacting Coinbase support and asking them if they can recover your account.

**Comment by johnjames333** [comment]
@lampkamonika 
contact me if you haven't recovered your wallet yet. check my profile

**Comment by lampkamonika** [comment]
I haven’t but I am not able to pay again

W dniu śr., 12.01.2022 o 09:00 wallet recovery ***@***.***>
napisał(a):

**Comment by Coding-Enthusiast** [comment]
Be careful of those who try to contact you privately like the comment I deleted. Never give your seed, keys or anything private to anyone on the internet.

**Comment by johnjames333** [comment]
@lampkamonika 
I will get 25% of the recovered fund only if I am able to recover your wallet, send me a gmail or telegram message we can discuss
telegram: @johnjames333 
anywalletrecovery@gmail.com
