### ISSUE TITLE
Could you please help me to find missing BTC wallet? Is it possible to find, when I know email addresses connected to the wallet, and when that mailboxes were already closed? Thank you. Donation from me, if it will be found. 

### ISSUE THREAD

**Issue by AndreyMakhanko** [Coding-Enthusiast/FinderOuter#24]

**Comment by Coding-Enthusiast** [comment]
There can't be any connection between an Email address and a bitcoin wallet, unless what you have is not a wallet but an account with a custodial service. In that case There isn't anything I can do to help you, sorry.  
It is also best to seek help for issues like this on public forums such as bitcointalk.org or reddit.com/r/bitcoin  
This place is for issues regarding this project only.

**Comment by AndreyMakhanko** [comment]
Thank you very much!

iPhone AM

14 апр. 2021 г., в 18:57, Coding Enthusiast ***@***.***> написал(а):

There can't be any connection between an Email address and a bitcoin wallet, unless what you have is not a wallet but an account with a custodial service. In that case There isn't anything I can do to help you, sorry.
It is also best to seek help for issues like this on public forums such as bitcointalk.org or reddit.com/r/bitcoin
This place is for issues regarding this project only.

**Comment by Mackklarson** [comment]
@AndreyMakhanko 
what is your wallet type??
if its blockchain wallet there may be some ways to recover your wallet

**Comment by AndreyMakhanko** [comment]
Hi,
It’s hot online wallet, and it’s no data kept besides the login name. 


iPhone AM

8 апр. 2022 г., в 22:01, wallet recovery service ***@***.***> написал(а):

@AndreyMakhanko
what is your wallet type??
if its blockchain wallet there may be some ways to recover your wallet

**Comment by Mackklarson** [comment]
@AndreyMakhanko 
exactly mention which online wallet you mean and write the  website address

**Comment by AndreyMakhanko** [comment]
If I remember which online wallet it is, and know website name, I’d not ask for the community support. It’s easy, right? I do not remember this data. Only email address as a login. And the password, of course. 

iPhone AM

9 апр. 2022 г., в 11:01, wallet recovery service ***@***.***> написал(а):

@AndreyMakhanko
exactly mention which online wallet you mean and write the website address

**Comment by Mackklarson** [comment]
@AndreyMakhanko 
as a last resort you can send your email to me, and I can check old online wallet to see if you have account in any of them.
if interested, send me email, you can find my email in my profile.

**Comment by AndreyMakhanko** [comment]
Great. My email connected to the wallet is ***@***.***
If there is any wallet with coins, 10% in the wallet is yours without any doubt, with deep gratitude from my side. 

iPhone AM

9 апр. 2022 г., в 13:22, wallet recovery service ***@***.***> написал(а):

@AndreyMakhanko
as a last resort you can send your email to me, and I can check old online wallet to see if you have account in any of them.
if interested, send me email, you can find my email in my profile.

**Comment by Mackklarson** [comment]
@AndreyMakhanko 
your email has been deleted 
as I said, send it to my gmail address or telegram

**Comment by AndreyMakhanko** [comment]
I don’t see here both your gmail and TG addresses. Let try again with my email address spelled through plain text: andrey dot makhanko at ponimanie dot org. Without spaces. 

iPhone AM

9 апр. 2022 г., в 16:19, wallet recovery service ***@***.***> написал(а):

@AndreyMakhanko
your email has been deleted
as I said, send it to my gmail address or telegram

**Comment by Coding-Enthusiast** [comment]
Please be careful who you trust. A random account on GitHub that was created 3 days ago with no history just to post this here is not so trustworthy...

**Comment by AndreyMakhanko** [comment]
Thank you very much for precaution! I appreciate that much. Indeed, I’m not very well in tech, but... I’m trying to be careful. Nobody gives him passwords, PIN, or bank card photo of both sides ;)
Thanks a lot once again!

iPhone AM

9 апр. 2022 г., в 18:03, Coding Enthusiast ***@***.***> написал(а):

Please be careful who you trust. A random account on GitHub that was created 3 days ago with no history just to post this here is not so trustworthy...
