### ISSUE TITLE
Terminal Commands

### ISSUE THREAD

**Issue by sezginyildirim91** [Coding-Enthusiast/FinderOuter#25]
I want to use it on the command line without an interface. Is this possible?

**Comment by Coding-Enthusiast** [comment]
> Is this possible?

Not without changing the code.  
Why do you not want to use the UI?

**Comment by sezginyildirim91** [comment]
Because I want to do automatic transactions. In interface mode this seems impossible.

**Comment by Coding-Enthusiast** [comment]
Could you elaborate more?

**Comment by sezginyildirim91** [comment]
> Could you elaborate more?

I want to apply experimental methods to find the WIF private key with more than 11 missing characters.
