### ISSUE TITLE
Given the 12 words, a wallet address and the m/49... code, is it possible to compute the initial public key/private key pair?

### ISSUE THREAD

**Issue by MarkRLV** [Coding-Enthusiast/FinderOuter#29]
I have a "KeepKey."  I know my 12 words.  When I log into beta.shapeshift.com, I can click "receive crypto" which gives me a wallet address and that m/49... string.  I know my password to log in.

From this information, can I compute the public key / private key that is inside my KeepKey?

**Comment by Coding-Enthusiast** [comment]
Yes, you should be able to do that.  
For KeepKey or any other software/hardware wallet that gives you a mnemonic you'll need the following information to recover all your private keys:  

1. The mnemonic (12, 15, 18 or 24 words)
2. If you used any words to extend the mnemonic (usually referred to as passphrase, not to be confused with the password used for encrypting the wallet file or to log in)
3. The mnemonic algorithm (almost always  like KeepKey it is BIP39 but if you used Electrum it is different, both of which we support. There is also aezeed which we don't support yet)
4. The derivation path (that is the `m/49'/0'/0'/0` for example)

You should be able to find 3&4 on the wallet's website or github repository or simply ask their devs or on a forum. However if you are missing the derivation path (4) you can use FinderOuter to try and figure it out if you have at least an address or child key from your wallet using the **Missing BIP32 path** option.
