### ISSUE TITLE
No clear instruction on how to run on Mac OS

### ISSUE THREAD

**Issue by drnick30** [Coding-Enthusiast/FinderOuter#32]
I can't seem to figure out how to run this on Mac OS, bearing in mind that I have zero knowledge on this.

I downloaded the binary file, ran terminal at the folder and used this command: dotnet FinderOuter

I get this error:
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-FinderOuter does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by Coding-Enthusiast** [comment]
If you are compiling the project yourself (have .net installed) you can run it by using `dotnet FinderOuter` but if you are downloading the binaries I provided (don't need installed .net) you should run it by using `./FinderOuter`.  
I don't have Mac OS to test but it seems like similar to Linux you need to provide execute permissions before running .net applications, and the command is different: `sudo chmod +x FinderOuter`
