### ISSUE TITLE
BIP38 encryption password recovery

### ISSUE THREAD

**Issue by Noname400** [Coding-Enthusiast/FinderOuter#36]
Hello. you can help to make a password guessing for BIP 38
I have a key, but it's encrypted.
your utility will be even more useful with the addition of this functionality.
I am currently using a program written in python.
the speed is bad.
thanks for any help.

**Comment by Coding-Enthusiast** [comment]
I will add this option eventually.  

The challenge is that all the recovery options I've implemented so far are using my own implementations of the underlying cryptography for maximize efficiency. BIP38 would be the same; scrypt, ECC and SHA256 are already implemented but AES is not and it is a complicated algorithm.  

> the speed is bad.

BIP38 is a very expensive algorithm and speed is expected to be bad.

**Comment by Noname400** [comment]
спасибо. буду ждать
