### ISSUE TITLE
p2sh recovery

### ISSUE THREAD

**Issue by Espresso0org** [Coding-Enthusiast/FinderOuter#37]
Hello.i have a p2sh wallet .i lost 4 character of private key and i know they position.i tried your software but it cant recover them.also i tried another wallet but it works well .maybe p2sh is the problem to recover?my private key starts with (L4A3.........)
Can you help me?

**Comment by Coding-Enthusiast** [comment]
> it cant recover them.

Did the program print any kind of error or did it just fail to find any key?  
If it is the former please tell me what the error was but if it is the later then either the missing positions are wrong or other characters in your private key may be wrong. Try changing the position or play around with other characters and try again. Search for 4 characters should take a second so you're in luck.

**Comment by Espresso0org** [comment]
It just said failed to find key.how can i conversation with you private?i want to show you sth.

**Comment by Espresso0org** [comment]
Im pretty sure my missed characters and positions are correct.also im pretty sure about known characters.i dont know why it cant find my key.its really huge money.i really need your help and i promiss give you good award.i cant tell you more information here.i lost only 4 characters.i need contact you privat
