### ISSUE TITLE
Recover time

### ISSUE THREAD

**Issue by Espresso0org** [Coding-Enthusiast/FinderOuter#38]
Hello.i started to recover a key with 11 characters lost almost between the private key.and it starts with K.i forget to calculate the time and i cant stop the procces because it spend 5~6 hours.my cpu is core i7 8700.can just tell me how much it gonna work?

**Comment by Espresso0org** [comment]
The total characters to check is 24,986,644,000,165,537,792  
With core i7 8700 and 12 core usage at 100%

**Comment by Coding-Enthusiast** [comment]
Unfortunately FinderOuter doesn't have time prediction yet. See #30 
But 11 characters is just too big to recover using CPU. It would take years to finish.
