### ISSUE TITLE
TextBoxes don't accept Chinese/Japanese characters

### ISSUE THREAD

**Issue by Coding-Enthusiast** [Coding-Enthusiast/FinderOuter#4]
This is possibly an Avalonia issue and is important in BIP-39 recovery option.

**Comment by bigdaddy975** [comment]
Thank you.

**Comment by Coding-Enthusiast** [comment]
Knwon issues in AvaloniaUI https://github.com/AvaloniaUI/Avalonia/issues/3780, https://github.com/AvaloniaUI/Avalonia/issues/5111
