### ISSUE TITLE
AddrComp

### ISSUE THREAD

**Issue by Espresso0org** [Coding-Enthusiast/FinderOuter#40]
Is it helpful to enter address Comp for recovering base58 ?

**Comment by Coding-Enthusiast** [comment]
You should enter the address you have, if it were created using a uncompressed public key or if it is another type such as P2SH-P2WPKH then choosing compressed address is not going to work.

**Comment by Espresso0org** [comment]
I lost 7 characters and i know they position well.also i have my compAddress.first time i search without enter addressComp.it show me about 1000 result but no one was my private key.this time i started to search with my addressComp.Do you think its gonna help me this time?

**Comment by Coding-Enthusiast** [comment]
No, it won't change a thing because the keys won't be checked against the given address. I could possibly change this with a downside of slight performance hit.

**Comment by Espresso0org** [comment]
What about public key?its helpful?

**Comment by Coding-Enthusiast** [comment]
Yes, using public key would skip 2 hashes that are required to compute an address and could slightly improve speed.
