### ISSUE TITLE
Does this application support Etherium?

### ISSUE THREAD

**Issue by Vasya3** [Coding-Enthusiast/FinderOuter#42]
I tried to find the last word in the SEED phrase for the Etherium wallet, but I ran into the problem "Invalid extra input or input type AddrComp". Is it possible to fix this somehow, or is this code not suitable for Etherium?
![1](https://user-images.githubusercontent.com/97354442/148652538-46951e1c-10be-44ed-97fb-2649b7f730a2.PNG)

**Comment by Coding-Enthusiast** [comment]
No, altcoins are not supported yet.
