### ISSUE TITLE
API / command line version

### ISSUE THREAD

**Issue by MonkishMan** [Coding-Enthusiast/FinderOuter#43]
hi is there a command line version of the software? or some kind of API? I would like to be able to run multiple searches without using the user interface.

**Comment by Coding-Enthusiast** [comment]
No. Because the point of this project is to simplify everything so that there is no need for command line.  
If you want to recover different keys you have to do it one by one, otherwise if it is same key with different changes it could be implemented if you explain what exactly you are trying to do.

**Comment by MonkishMan** [comment]
I have a partial key and need to try different combinations. I don't know which bits are correct so I need to run different combinations. I'm trying manually through the user interface but it's really time consuming. If I could automate it with code it would really help.

**Comment by MonkishMan** [comment]
I suppose you have unit tests and I could possibly write some similar code to interact with the main library?

**Comment by Coding-Enthusiast** [comment]
You could write a loop and call [Find](https://github.com/Coding-Enthusiast/FinderOuter/blob/04c60fce5879f7a5a7fe970b01f366f750d224a5/Src/FinderOuter/Services/Base58Sevice.cs#L1390) method (works on any of the service classes) repeatedly with different keys.

**Comment by MonkishMan** [comment]
That would be great. Thanks

**Comment by MonkishMan** [comment]
hi, im struggling to understand the code here, I can call the 'Find' method, but I don't understand where the results are meant to be? Sorry I'm more of a backend dev so this reactive stuff is pretty new to me. does the report object not contain the results of the search? its seems to get to the right states using sample keys i feed it, but I just dont see how to output the results its found.

**Comment by MonkishMan** [comment]
ok will give it a go, thanks

**Comment by MonkishMan** [comment]
Thanks for your help, I was able to cobble something together that did what I needed. Managed to get it to loop around and try many combinations with a single click of a button.
