### ISSUE TITLE
help me!! 

### ISSUE THREAD

**Issue by Ango87** [Coding-Enthusiast/FinderOuter#44]
I lost 14 characters of my private key How do I recover the lost characters? 
it's like this for example:
12 **** 3456789123 *** 123456788 **** 123456 *** 1234567
please tell me how to extract this program to find the missing 14 characters

**Comment by Coding-Enthusiast** [comment]
14 characters is too much to recover with FinderOuter.

**Comment by ipensatori** [comment]
If one knows the precise order and it's just digits, surely this is possible?
