### ISSUE TITLE
please compile new version

### ISSUE THREAD

**Issue by Noname400** [Coding-Enthusiast/FinderOuter#45]
please compile new version

**Comment by Coding-Enthusiast** [comment]
Need to do some tests and add parallelism to the new option before I can release next version. Shouldn't take more than a couple of days.

**Comment by Noname400** [comment]
thanks for adding BIP 38
I was looking forward to this.

**Comment by Coding-Enthusiast** [comment]
There you go: [v0.13.0](https://github.com/Coding-Enthusiast/FinderOuter/releases/tag/v0.13.0.0)

**Comment by Noname400** [comment]
Thx.
