### ISSUE TITLE
Missing BIP38 EC mult decryption mode

### ISSUE THREAD

**Issue by Talant047** [Coding-Enthusiast/FinderOuter#49]
Your program- Missing Bip38 pass- refuses to work. Check the error-Invalid prefix.
I used this-

1AMYsRoWDAr5fAB49UUJUgse5LRZ2c82Qv

6PnWt89G6WGAr2mK5nEAPtSe7Q1EvK1W2Txodd9Y1KDEDJgWd6hg2Xv6nt

1945

![bip-38](https://user-images.githubusercontent.com/50215875/152864446-c394ff31-2ee3-4809-81a3-360a79685110.png)

**Comment by Coding-Enthusiast** [comment]
That's because your encrypted key uses a different BIP38 mode (EC multiply) that I didn't think anybody used so there is no code for it. The algorithm is slightly different and complicated.  

Thanks for the report. I'll see what I can do to implement this.

**Comment by Talant047** [comment]
Thanks, I'll wait.
