### ISSUE TITLE
mutithreading

### ISSUE THREAD

**Issue by emmanuel211g** [Coding-Enthusiast/FinderOuter#55]
how many cpu can your program handle cuz i have aws 64 vcpu and im getting 600 m/s. can it handle more cpu with out running mutiple copys

**Comment by Coding-Enthusiast** [comment]
I can tell you that the framework doesn't differentiate between multiple cores in a CPU and multiple physical CPUs. As long as it can access them, it should be able to create an appropriate thread pool and spread the work among all those units.
