### ISSUE TITLE
Is it possible to find the wallet address from 12 recovery phrase (mnemonic)?

### ISSUE THREAD

**Issue by huynhvanquy** [Coding-Enthusiast/FinderOuter#57]
Do you have any solution or direction to do this, please share it with me. Thank you!

Example:
- From: gravity throw patient proud rocket bonus hair laundry number jaguar exist tower

---> return wallet address: 0xFBc84Ca6fBD7d9F6d0BbF0E1E1bDE987C2eEF7E4

**Comment by Coding-Enthusiast** [comment]
The address you posted is from an altcoin while FinderOuter does not yet support altcoins.  
If this were a bitcoin wallet, the _Missing BIP32 path_ option could figure out the derivation path if you have the full mnemonic and the address.

**Comment by huynhvanquy** [comment]
Thank you so much!
