### ISSUE TITLE
Help me recover my bitcoins please! Pay reward!

### ISSUE THREAD

**Issue by aecio1987** [Coding-Enthusiast/FinderOuter#60]
My cell phone was stolen. I managed to erase my data before they had access. However, when accessing my Trust Wallet, only
I remembered the words from my main wallet and I don't remember two wallets. But I have bitcoin send keys for both. Could you help me to recover? I tried FinderOuter but as I don't know the 12 words, it's hard. I pay 1 bitcoin for the help if I can recover the accounts. I await your contact. Thanks!

**Comment by Coding-Enthusiast** [comment]
Same as #59
