### ISSUE TITLE
Running on Mac OS

### ISSUE THREAD

**Issue by bane77111** [Coding-Enthusiast/FinderOuter#70]
Hi, can someone please help me and explain how to run this on Mac book pro. I did:  Step 2: Download and build

If you cannot or do not want to build you can go to [releases](https://github.com/Coding-Enthusiast/FinderOuter/releases) where the ready to run binaires are found for 3 different x64 operating systems: Windows, Linux and MacOS. the other two files named Source code.zip and Source code.tar.gz are the project's source code that GitHub automatically adds at that release version's commit.
Now i have this files: 
<img width="295" alt="Screen Shot 2023-03-08 at 05 20 50" src="https://user-images.githubusercontent.com/81524585/223618798-48d14ca6-ff24-49d5-a625-5522c1c2d72c.png">                                                                                                        
  

How to go on from here? Thanks in advance!

**Comment by Coding-Enthusiast** [comment]
I've never used Mac OS but AFAIK you should be able to run FinderOuter similar to Linux meaning you can run it using `./FinderOuter` from your terminal. You may need to run `chmod +x` on the executable first.

**Comment by bane77111** [comment]
> I've never used Mac OS but AFAIK you should be able to run FinderOuter similar to Linux meaning you can run it using `./FinderOuter` from your terminal. You may need to run `chmod +x` on the executable first.

Thanks! Its working:  chmod +x FinderOuter    Just for the first time have to use: sudo ./FinderOuter
