### ISSUE TITLE
FinderOuter.exe has stopped working 

### ISSUE THREAD

**Issue by Goldman77** [Coding-Enthusiast/FinderOuter#76]
I am using Windows 7. When I run FinderOuter it gives an error: FinderOuter.exe has stopped working.What do I have to do?

**Comment by Coding-Enthusiast** [comment]
Windows 7 stopped being support about 4 years ago. You should be able to use older FinderOuter versions (<0.18), otherwise either upgrade your Windows or better use a Linux OS.
