### ISSUE TITLE
پیدا کردن کلید کیف پول

### ISSUE THREAD

**Issue by Jafbaz** [Coding-Enthusiast/FinderOuter#87]
گم کردن کلید های بازیابی کیف پول تراست ولت 
ولی آدرس واریز ارز bnbبه کیف پول را دارم

**Comment by seyed18401840** [comment]
سلام. وقت بخیر.شرایط

در تاریخ سه‌شنبه ۱۶ ژوئیه ۲۰۲۴، ۱۲:۰۸ ق.ظ Jafbaz ***@***.***>
نوشت:
